version: '3.8'
services:
  app:
    image: amit19w/socialnetwork
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mailhog
    environment:
      SPRING_MAIL_HOST: host.docker.internal
      SPRING_MAIL_PORT: 1025
      APP_FRONTEND_URL: http://localhost:3000

  frontend:
    image: amit19w/se-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: login-register
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: